services:
  web:
    build: .
    container_name: pdlc
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
      NEXT_PUBLIC_APP_URL: "http://localhost:3000"
      # IMPORTANT : URL Neon (pooled)
      DATABASE_URL: "postgresql://neondb_owner:npg_zycmi8CLu9dN@ep-steep-brook-ag8lmre8-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&pgbouncer=true&connect_timeout=10"
    restart: unless-stopped
